### ISSUE TITLE
Found problems with add botman to existing projects

### ISSUE THREAD

**Issue by 4UForever** [botman/studio-addons#30]
I used Laravel 5.7 and when I run **composer require botman/stodio-addons** it appear this error
`Symfony\Component\Debug\Exception\FatalErrorException  : Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub)

  at C:\mychatbot\vendor\botman\studio-addons\src\Console\Commands\BotManCacheClear.php:50
    46|         }
    47|
    48|         $this->info('BotMan cache cleared!');
    49|     }
  > 50| }
    51|

   Whoops\Exception\ErrorException  : Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub)

  at C:\mychatbot\vendor\botman\studio-addons\src\Console\Commands\BotManCacheClear.php:50
    46|         }
    47|
    48|         $this->info('BotMan cache cleared!');
    49|     }
  > 50| }
    51|

PHP Warning:  Uncaught ErrorException: Declaration of BotMan\Studio\Console\Commands\BotManCacheClear::handle(Illuminate\Filesystem\Filesystem $files) should be compatible with Illuminate\Console\GeneratorCommand::handle() in C:\mychatbot\vendor\botman\studio-addons\src\Console\Commands\BotManCacheClear.php:50
Stack trace:
#0 C:\mychatbot\vendor\composer\ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Declaration of ...', 'C:\\mycha...', 50, Array)
#1 C:\mychatbot\vendor\composer\ClassLoader.php(444): include()
#2 C:\mychatbot\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\Work\\Git\\cha...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('BotMan\\Studio\\C...')
#4 [internal function]: spl_autoload_call('BotMan\\Studio\\C...')
#5 C:\mychatbot\vendor\laravel\framework\src\Illuminate\Container\Container.php(767): ReflectionClass->__construct('BotMan\\Studio\\C in C:\mychatbot\vendor\botman\studio-addons\src\Console\Commands\BotManCacheClear.php on line 50
PHP Fatal error:  Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub) in C:\mychatbot\vendor\botman\studio-addons\src\Console\Commands\BotManCacheClear.php on line 50
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255`

But if I running this command, **composer require botman/stodio-addons "~1.2.1"** no errors found (specific version 1.2.1). may be this version (1.4.0) has some bugs. could you please help to fix.

**Comment by stefandanaita** [comment]
Version `1.3.0` is also working. `v1.4.0` is broken.

**Comment by jeroenherczeg** [comment]
Got the same issue, 1.4 is not working

`PHP Warning:  Uncaught ErrorException: Declaration of BotMan\Studio\Console\Commands\BotManCacheClear::handle(Illuminate\Filesystem\Filesystem $files) should be compatible with Illuminate\Console\GeneratorCommand::handle() in /home/hadary/Code/hadary/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php:50
Stack trace:
#0 /home/hadary/Code/hadary/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Declaration of ...', '/home/hadary/Co...', 50, Array)
#1 /home/hadary/Code/hadary/vendor/composer/ClassLoader.php(444): include()
#2 /home/hadary/Code/hadary/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/hadary/Co...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('BotMan\\Studio\\C...')
#4 [internal function]: spl_autoload_call('BotMan\\Studio\\C...')
#5 /home/hadary/Code/hadary/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('BotMan\\Studio\\C...')
#6 /home/hadary in /home/hadary/Code/hadary/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php on line 50
PHP Fatal error:  Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub) in /home/hadary/Code/hadary/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php on line 50

   Symfony\Component\Debug\Exception\FatalErrorException  : Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub)

  at /home/hadary/Code/hadary/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php:50
    46|         }
    47| 
    48|         $this->info('BotMan cache cleared!');
    49|     }
  > 50| }
    51|


   Whoops\Exception\ErrorException  : Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub)

  at /home/hadary/Code/hadary/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php:50
    46|         }
    47| 
    48|         $this->info('BotMan cache cleared!');
    49|     }
  > 50| }
    51|

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
`

Downgraded to 1.3 for now
